project:
  type: website
  output-dir: docs

website:
  title: "Dr. Cat Fong"
  navbar:
    right:
      - href: index.qmd
        text: Hello!
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Current Projects
      - href: publications.qmd
        text: Papers

format:
  html:
    theme: styles.scss
    mainfont: Montserrat
    toc: true


editor: visual

