project:
  type: website
  output-dir: docs

website:
  title: "Dr. Cat Fong"
  site-url: https://catfong.github.io
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: styles.scss
    mainfont: Source Sans 3
    toc: true
    link-external-newwindow: true

editor: visual
