project:
  type: website
  output-dir: docs

website:
  title: "hello world"
  navbar:
    left:
      - href: index.qmd
        text: Hello!
      - href: about.qmd
        text: NOOOOO
      - href: publications.qm
        text: Papers

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

